### ISSUE TITLE
Najboljši igralec

### ISSUE THREAD

**Issue by blazdob** [dimes123/kosarkaska-ekipa#13]
uporabnik iz seznama nasprotnih ekip izbere eno ekipo, nato mu da seznam vseh tekem, v katerih je ekipa igrala proti tej ekipi, to nato izbere in mu vrne najboljšega igralca z te tekme. 
torej izpiše igralca z največ točkami, z največ podajami....

**Comment by dimes123** [comment]
Narejeno
