### ISSUE TITLE
2.) najboljši igralec na tekmi, 2 majhni napakici ;)

### ISSUE THREAD

**Issue by blazdob** [dimes123/kosarkaska-ekipa#6]
1. Vrjetno bi bilo dobro da se uporabniku napiše, da je ime ekipe celoti, obenem pa če se uporabik zmoti, ga vrže ven, mogoče bi bilo bolj smiselno, da uporabnika ponovno vpraša po ekipi. 
-to enako velja pri 1.) če izberemo ime igralca, ki ga nimava v bazi. vrže spet na začetek, bi bilo bolje, da te ponovno upraša po igralcu.

2. Če ob izbiri datumov izberemo preveliko število se najin program sesuje, to ni fajn ;)

**Comment by dimes123** [comment]
Done
